apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shrek
  name: shrek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shrek
  strategy: {}
  template:
    metadata:
      labels:
        app: shrek
    spec:
      containers:
      - image: shrek:latest
        name: shrek
        imagePullPolicy: Never
        env:
        - name: QUOTES_PATH
          value: "/tmp"
        resources: {}
        volumeMounts:
          - mountPath: /tmp
            name: shrek-cm
      volumes:
      - name: shrek-cm
        configMap:
          name: shrek-cm