apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: translate
  name: translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translate
  strategy: {}
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
      - image: translate:latest
        name: translate
        imagePullPolicy: Never
        resources: {}
        envFrom:
          - configMapRef:
              name: translate-cm